### ISSUE TITLE
很低的AP和检测结果

### ISSUE THREAD

**Issue by ByWxw** [ouyanghuiyu/Thundernet_Pytorch#1]
您好，我尝试使用您的代码跑VOC，但是得到了很低的结果（AP，AP50等，接近于0），检测结果也不是很好，请问您出现过这种情况吗？谢谢！

**Comment by ouyanghuiyu** [comment]
你更新一下代码 在试试看，我也在尝试，目前结果不太好，只有40的AP

**Comment by ByWxw** [comment]
嗯嗯，好的，谢谢您！






------------------



王伟刚

北京邮电大学/研究生/电子工程学院



13051897254

北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by ouyanghuiyu** [comment]
你好 我提供了预训练模型，并更新了代码，结果较之前要很多

**Comment by ByWxw** [comment]
嗯嗯，好的，我会马上实验，非常感谢您的工作！我也会持续地跟踪算法。






------------------



王伟刚

北京邮电大学/研究生/电子工程学院



13051897254

北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by PCRKTY** [comment]
您好，请问你解决了AP和Results很低的问题了吗？
