### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by yufeilongyuan** [ouyanghuiyu/Thundernet_Pytorch#2]
If I train my own data, but it is different from the number of categories in the coco data set, where should I modify it? Thank you

**Comment by ouyanghuiyu** [comment]
try chang the config.py for your own dataset!

**Comment by yufeilongyuan** [comment]
By the way, when do I support the NCNN framework? Thank you

**Comment by ouyanghuiyu** [comment]
Now the model doesn't work very well！ I'll try if it works！

**Comment by yufeilongyuan** [comment]
thanks
