### ISSUE TITLE
关于训练另外一个数据集

### ISSUE THREAD

**Issue by TianMingChen** [ouyanghuiyu/Thundernet_Pytorch#20]
你好，请问出现这个问题要怎么办？
训练VOC数据集正常可以训练，测试，但是
训练自己的数据，代码可以跑起来，loss不下降，AP为0

![image](https://user-images.githubusercontent.com/20785298/71509806-90bb0500-28c7-11ea-8e56-61e19a174506.png)

VOC2007

![voctest_1](https://user-images.githubusercontent.com/20785298/71509923-00c98b00-28c8-11ea-86ca-290c94b4355f.JPG)

**Comment by ouyanghuiyu** [comment]
学习率咋这么低

**Comment by TianMingChen** [comment]
> 学习率咋这么低
初始是1e-2，但是一开始就变为1e-6了
![image](https://user-images.githubusercontent.com/20785298/71511434-4b99d180-28cd-11ea-9fd2-9e4fb84f3a45.png)

**Comment by TianMingChen** [comment]
> 学习率咋这么低

好像是图片数量太少了，引起的
![image](https://user-images.githubusercontent.com/20785298/71511561-c82cb000-28cd-11ea-8ebe-db52d238a6e9.png)

**Comment by ouyanghuiyu** [comment]
可以改一下 warm up

**Comment by TianMingChen** [comment]
> 可以改一下 warm up

数据集一个650张图片，训练集：验证集：测试集=7：2：1；
warm up要怎么改比较合适?

**Comment by ouyanghuiyu** [comment]
把100改成20吧

**Comment by ouyanghuiyu** [comment]
100 改为 10 看看

**Comment by TianMingChen** [comment]
> 100 改为 10 看看

好的，我试一下

**Comment by ouyanghuiyu** [comment]
不行再改小点 或者batch小点

**Comment by TianMingChen** [comment]
> 不行再改小点 或者batch小点
嗯，我试了5，效果会比较好
