### ISSUE TITLE
something about result

### ISSUE THREAD

**Issue by 246yf87953246** [ouyanghuiyu/Thundernet_Pytorch#4]
hi，Thanks for your contributing！I train the model on KITTI dataset，only one class=‘car’；but the AP and AR are low，are 0.23 and 0.4 respectively；The FPS i test on 1050Ti are 50，is it any problem？

**Comment by ouyanghuiyu** [comment]
hi , I provided the snet146 pretrained model and optimized code,you can update code ,then train for your job
